sudo: required
services:
- docker
env:
  global:
  - VERSIONS="5.16,5.20,5.24"
  - secure: OezpHvhAPJimUNiL7hbh7VXpAeIz9NrdBApkSZRFlLa4kH9nCBYBn4FSQvUgdoz4PQGVwrQkOwJytQKblVLDKlrDgjnq5QT9OCyqYvD3XsiGipX8yjdQrHL91u/d4ZiPWiw9dC+62GSUrZvhwIuO4JP5CWPenZVpS9Ijt2NYn3OX3tTKE9/4Bg0IAi3Rmv3UGKqnJqgRGyfgBlAtxlWI+GRW5ltnEHQ3TXfufrr39yi2WQhE0/4UDW/AASAlF7S7Fa14IYK/mq+ne+c3sU/WbZlegj6a3Hh8Njt1dpAXIByxErZ6FrTzULTlZnfORhU0XeMB4UCCcbVhHDmS4Ul1jBKasNKBvGNC6F8PuXJztrpDTZYgDXnmOr7V+K/R/7H/samoDc+z5/dqH747gnXN5sa9VfpxtuzL3f/Gu3byyEvSGpHC63aogFNirHtVPcvHDJyVSxbiapC4Na/02tgYIPX52j3TqSuziO8kttcXgiy9Zx0DychMxsVW3eAHXQMCBlhUbsohbFP7Vj9vLR6fM3V3QIwp9AGECltFe1F1pvYTG5HwFRKJeWm1KhJedb/p9ojJQ0bsm0ulfcRcWkUaocig68jCTijLm7yXgh3XWuO/dfIe6I0YAcPnY74b+4LXstiuvP4oU7OKjNu2h7Uc6Of7owyMGOVEiyKEanYOhJs=
script:
- ". test/run"
notifications:
  slack:
    secure: mu8Op/pzPUDksVjz7kORwc2K4hg+DzeIonit+P+yIK7vqIxdXs5YYCX+zio35sb+tzVl1aX0NHERteSwyFXdpjj9rhjupnVIz12PS1mOsP3yjC3yeT+RoPgDEqlHsgviAw+cQ51Uhpdp03Ewn4bzpBU+cPOR02rsiHL4oL/7kZRIFKyIOMuO3jbp48isRMMGBrGhjHateF0hk/3E81BnllOUeHYz1GrYHg70DsXJFkxGrx6BhXPeZXkJ+EiYttZNf2w6RN6u/OjwGwAB0H019Wtv9/sfBTr4Tr3mlS4JYGUmBU8IdpAy/haLh/exQME2FToem4Y5Jj6OI3kWa4gCQc2SUHwU6rb62EzZwK0q36yztRtMQO9W3+o7XFRNU/CFiBVf3fn8zRNmiOj4t3us0p+Ac7blRn7r6QRhfYwkdimFP5KeNIlD86oqLsFVACjfgRb4Prj9xrYKlbFwFppWtI8MopTn5ffI5DTLdTBDcFrMvuUM5mEw9agi3wL4EGuUjlrLaR2zt+Q2NUS2njDS8iYSF76Y7jUsZyrXcT2TiJuoSYKg6j0TRBeZcihCtQ2WtLqrUL5JpxlEQ7O+cmwPtQKnr2EGc34zxn+nakE84TYGmyR9RwJPBN7wnNIBD01onY9gzNsB0qrteGoUxZeZo8DoubrOJa8GJLTyp3dg6u8=
